# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
# Usar a seguinte url no .env
# DATABASE_URL=postgresql://root:root@localhost:5432/bolico?schema=bolico_auth
